package network;

import com.esotericsoftware.kryo.Kryo;
import models.CollisionRect;
import models.Game;
import models.Item;
import models.NPC.NPC;
import models.NPC.NPCFriendships;
import models.User;
import models.animal.Animal;
import models.building.*;
import models.character.*;
import models.character.Character;
import models.date.Date;
import models.enums.*;
import models.food.Food;
import models.food.FridgeItem;
import models.food.Refrigerator;
import models.interactions.*;
import models.map.Map;
import models.map.Particle;
import models.map.Tile;
import models.map.Weather;
import models.resource.*;
import models.shops.*;
import models.tool.*;
import models.workBench.Inprocess;
import models.workBench.ItemKinds;
import models.workBench.RecipeInfo;
import models.workBench.WorkBench;
import network.Lobby.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class KryoRegistrations {
    public static void registerClasses(Kryo kryo) {
        kryo.register(Game.class);
        kryo.register(User.class);
        kryo.register(Gender.class);
        kryo.register(Question.class);
        kryo.register(SecurityQuestion.class);
        kryo.register(Map.class);
        kryo.register(Tile.class);
        kryo.register(Date.class);
        kryo.register(Weather.class);

        kryo.register(BackpackType.class);
        kryo.register(Integer.class);
        kryo.register(Animal.class);
        kryo.register(Building.class);
        kryo.register(Greenhouse.class);
        kryo.register(Shop.class);
        kryo.register(Buff.class);
        kryo.register(Character.class);
        kryo.register(Inventory.class);
        kryo.register(InventorySlot.class);
        kryo.register(Question.class);
        kryo.register(Skill.class);
        kryo.register(Trashcan.class);
        kryo.register(TrashcanType.class);
        kryo.register(Date.class);
        kryo.register(AnimalType.class);
        kryo.register(BackpackType.class);
        kryo.register(CageType.class);
        kryo.register(CookingRecipes.class);
        kryo.register(CropType.class);
        kryo.register(DaysOfTheWeek.class);
        kryo.register(Direction.class);
        kryo.register(FishType.class);
        kryo.register(FriendshipLevel.class);
        kryo.register(Gender.class);
        kryo.register(ItemType.class);
        kryo.register(NpcDialog.class);
        kryo.register(NpcInfo.class);
        kryo.register(Recipe.class);
        kryo.register(RequestConstants.class);
        kryo.register(Season.class);
        kryo.register(SecurityQuestion.class);
        kryo.register(ShopType.class);
        kryo.register(StoneType.class);
        kryo.register(TileType.class);
        kryo.register(ToolType.class);
        kryo.register(TrashcanType.class);
        kryo.register(TreeType.class);
        kryo.register(WeatherState.class);
        kryo.register(WorkBenchType.class);
        kryo.register(FridgeItem.class);
        kryo.register(Refrigerator.class);
        kryo.register(Interact.class);
        kryo.register(InteractTRADE.class);
        kryo.register(InteractFLOWER.class);
        kryo.register(InteractGIFT.class);
        kryo.register(InteractHUG.class);
        kryo.register(InteractMARRIGE.class);
        kryo.register(InteractTALK.class);
        kryo.register(Iteractions.class);
        kryo.register(Map.class);
        kryo.register(Particle.class);
        kryo.register(Tile.class);
        kryo.register(Weather.class);
        kryo.register(NPC.class);
        kryo.register(NPCFriendships.class);
        kryo.register(BuildingReference.class);
        kryo.register(Crop.class);
        kryo.register(Resource.class);
        kryo.register(ShippingBin.class);
        kryo.register(Stone.class);
        kryo.register(Tree.class);
        kryo.register(BlackSmith.class);
        kryo.register(Carpenter.class);
        kryo.register(FishShop.class);
        kryo.register(JojaMart.class);
        kryo.register(Marnie.class);
        kryo.register(Pierre.class);
        kryo.register(ShopAnimals.class);
        kryo.register(ShopBackpacks.class);
        kryo.register(ShopCages.class);
        kryo.register(ShopCookingRecipes.class);
        kryo.register(ShopFishingPoleUpgrades.class);
        kryo.register(ShopFoods.class);
        kryo.register(ShopItem.class);
        kryo.register(ShopRecipes.class);
        kryo.register(ShopTool.class);
        kryo.register(ShopToolUpgrades.class);
        kryo.register(ShopTrashcanUpgrades.class);
        kryo.register(StarDrop.class);
        kryo.register(Axe.class);
        kryo.register(FishingPole.class);
        kryo.register(Hoe.class);
        kryo.register(MilkPail.class);
        kryo.register(Pickaxe.class);
        kryo.register(Scythe.class);
        kryo.register(Shear.class);
        kryo.register(Tool.class);
        kryo.register(WateringCan.class);
        kryo.register(Inprocess.class);
        kryo.register(ItemKinds.class);
        kryo.register(WorkBench.class);
        kryo.register(Item.class);
        kryo.register(Food.class);





        kryo.register(network.Requsets.class);
        kryo.register(Network.updateGame.class);
        kryo.register(List.class);
        kryo.register(ArrayList.class);
        kryo.register(network.NetworkRequest.class);
        kryo.register(HashMap.class);
        kryo.register(models.enums.graphic.BackgroundMusic.class);
        kryo.register(models.CollisionRect.class);
        kryo.register(models.map.Tile[][].class);
        kryo.register(models.map.Tile[].class);
        kryo.register(CollisionRect.class);
        kryo.register(com.google.gson.internal.LinkedTreeMap.class);
        kryo.register(java.util.LinkedHashMap.class);
        kryo.register(MapUpdate.class);
        kryo.register(Lobby.class);
        kryo.register(LobbyType.class);
        kryo.register(LobbyPrivacy.class);
        kryo.register(AddUserLobbyRequest.class);
        kryo.register(LobbyRequest.class);
        kryo.register(LeaveLobbyRequest.class);
        kryo.register(OnlineClientResponse.class);
        kryo.register(OfflineRequest.class);
        kryo.register(VotingRequest.class);
        kryo.register(VoteType.class);
        kryo.register(GetVote.class);
        kryo.register(Vote.class);
        kryo.register(Chat.class);
        kryo.register(ScoreTableRefresh.class);
        kryo.register(RecipeInfo.class);
        kryo.register(FriendShip.class);
        kryo.register(GiftSent.class);
    }
}
