package models.enums;

public enum ItemType {
    Wood(10,"wood",0 , false),
    HardWood(10,"hard wood" , 0 , false),
    Pony(0,"pony" , 0 , false) ,
    Stone(20 , "stone" , 0 , false),
    Iron(20 , "iron" , 0 , false),
    Fur(0 , "fur" , 0 , false),
    Sardine(40,"sardine" , 0 , false),
    DeluxeRetainingSoil(300,"deluxe retaining soil" , 0 , false),
    SpeedGro(123,"speed gro",0,false),
    AppleSapling(335,"apple sapling",0,false),
    CherrySapling(3000,"cherry sapling",0,false),
    ApricotSapling(300,"apricot sapling",0,false),
    Bouquet(100,"bouquet" , 0 , false),
    WineBottle(46 , "botri ab shangooli" , 0 , false),
    QualityRetainingSoil(500,"quality retaining soil" , 0 , false),
    Pumpkin(320 , "pumpkin" , 0 , false),
    OrangeSapling(120,"orange sapling",0,false),
    BasicRetainingSoil(400,"basic retaining soil" , 0 , false),

    WeddingRing(20000,"wedding ring" , 0 , false),
    PeachSapling(200,"peach sapling" , 0 , false),
    IronOre(10 , "iron ore" , 0 , false),
    PomegranateSapling(300,"pomegranate sapling",0,false),
    CopperOre(5 , "copper ore" , 0 , false),
    GoldOre(25 , "gold ore" , 0 , false),
    Corn(40,"corn" , 0 , false),
    Pickle(20,"pickle" , 10 , true),
    Tomato(30,"tomato" , 0 , false),
    Fiber(100,"fiber" , 0 , false),
    Potato(30,"potato" , 0 , false),
    Blueberry(30,"blueberry" , 0 , false),
    Melon(30,"melon" , 0 , false),
    Apricot(30,"apricot" , 0 , false),
    RedCabbage(400,"red cabbage" , 0 , false),
    Radish(20, "radish" , 0 , false),
    Amaranth(30,"amaranth" , 0 , false),
    Kale(35,  "kale" , 0 , false),
    Beet(20, "beet" , 0 , false),
    Parsnip(34, "parsnip" , 0 , false),
    EggPlant(10,"egg plant" , 0 , false),
    Flounder(100,"flounder" , 0 , false),
    MidnightCarp(500,"midnight carp" , 0 , false),
    IridiumOre(100,"iridium ore" , 0 , false),
    BeeHouse(200,"bee house" , 0 , false),
    Wheat(50 , "wheat" , 0 , false),
    Gold(20 , "gold" , 0 , false),
    Quartz(25 , "quartz" , 0 , false),
    WaterSprinkler(300 , "water sprinkler" , 0 , false),
    Plant(200 , "plant" , 0,false),
    Salmon(75,"salmon" , 0 , false),
    Diamond(750 , "diamond" , 0 ,false),
    BlueJazz(50,"blue jazz" , 45 , true),
    Carrot(35,"carrot" , 75 , true),
    Fish(400 , "fish" , 0 , false),
    JojaCola(0,"joja cola" , 0 , false),
    Sugar(0,"sugar" , 0 , false),
    WheatFlour(0,"wheat flour" , 0 , false),
    Rice(0,"rice" , 0 , false),
    CauliFlower(175 , "cauli flower" , 75 , false),
    CoffeeBean(15 , "coffee bean" , 0 , false),
    CommonMushroom(40 , "common mushroom" , 38 , true),
    Daffodil(30 , "daffodil" , 0 , false),
    Dandelion(40 , "dandelion" , 25 , true),
    Leek(60 , "leek",40 , true),
    Moral(150 , "moral", 20 , true),
    SalmonBerry(5 , "salmon berry", 25 , true),
    Hay(0,"hay" , 0 , false),
    SpringOnion(8  ,"spring onion" , 13 , true),
    WildHorseradish(50  , "wildHorseradish" , 13 , true),
    FiddleHead(90 , "fiddle head" ,25 , true),
    RedMushroom(75, "red mushroom", -50, true),
    SpiceBerry(80, "spice berry", 25, true),
    SweetPea(50, "sweet pea", 0, false),
    Blackberry(25, "blackberry", 25, true),
    Chanterelle(160, "chanterelle", 75, true),
    Hazelnut(40, "hazelnut", 38, true),
    PurpleMushroom(90, "purple mushroom", 30, true),
    WildPlum(80, "wild plum", 25, true),
    Crocus(60, "crocus", 0, false),
    CrystalFruit(150, "crystal fruit", 63, true),
    Holly(80, "holly", -37, true),
    SnowYam(100, "snow yam", 30, true),
    WinterRoot(70, "winter root", 25, true),
    Grape(30 , "grape" , 10 , true),
    EarthCrystal(50 , "earth crystal" , 0 , false),
    FrozenTear(75 , "frozen tear" , 0 , false),
    FireQuartz(100 , "fire quartz" , 0 , false),
    Emerald(250 , "emerald" , 0 , false),
    Aquamarine(180 , "aquamarine" , 0 , false),
    Ruby(250  ,"ruby", 0 , false),
    Amethyst(100 , "amethyst" , 0 , false),
    Topaz(80 , "topaz" , 0 , false),
    Jade(200 , "jade" , 0 , false),
    PrismaticShard(2000 , "prismatic shard" , 0 , false),
    Copper(5 , "copper" , 0 , false),
    Iridium(100 , "iridium", 0 , false),
    JazzSeed(0, "jazz seed" , 0 ,false),
    CarrotSeed(0 , "carrot seed" , 0 , false),
    CauliflowerSeed(0, "cauliflower seed", 0, false),
    GarlicSeed(0, "garlic seed", 0, false),
    BeanStarter(0, "bean starter", 0, false),
    KaleSeed(0, "kale seed", 0, false),
    ParsnipSeed(0, "parsnip seed", 0, false),
    PotatoSeed(0, "potato seed", 0, false),
    RhubarbSeed(0, "rhubarb seed", 0, false),
    StrawberrySeed(0, "strawberry seed", 0, false),
    TulipBulb(0, "tulip bulb", 0, false),
    RiceShoot(0, "rice shoot", 0, false),
    BlueberrySeed(0, "blueberry seed", 0, false),
    CornSeed(0, "corn seed", 0, false),
    HopsStarter(0, "hops starter", 0, false),
    PepperSeed(0, "pepper seed", 0, false),
    MelonSeed(0, "melon seed", 0, false),
    PoppySeed(0, "poppy seed", 0, false),
    RadishSeed(0, "radish seed", 0, false),
    RedCabbageSeed(0, "red cabbage seed", 0, false),
    StarfruitSeed(0, "starfruit seed", 0, false),
    SpangleSeed(0, "spangle seed", 0, false),
    SummerSquashSeed(0, "summer squash seed", 0, false),
    SunflowerSeed(0, "sunflower seed", 0, false),
    TomatoSeed(0, "tomato seed", 0, false),
    WheatSeed(0, "wheat seed", 0, false),
    AmaranthSeed(0, "amaranth seed", 0, false),
    ArtichokeSeed(0, "artichoke seed", 0, false),
    BeetSeed(0, "beet seed", 0, false),
    BokChoySeed(0, "bok choy seed", 0, false),
    BroccoliSeed(0, "broccoli seed", 0, false),
    CranberrySeed(0, "cranberry seed", 0, false),
    EggplantSeed(0, "eggplant seed", 0, false),
    FairySeed(0, "fairy seed", 0, false),
    GrapeStarter(0, "grape starter", 0, false),
    PumpkinSeed(0, "pumpkin seed", 0, false),
    YamSeed(0, "yam seed", 0, false),
    RareSeed(0, "rare seed", 0, false),
    PowderMelonSeed(0, "powder melon seed", 0, false),
    AncientSeed(0, "ancient seed", 0, false),
    MixedSeed(0, "mixed seed", 0, false),
    Acorns(0 , "acorns" , 0 , false),
    MapleSeed(0 , "maple seed" , 0 , false),
    PineCones(0 , "pine cones" , 0 , false),
    MahoganySeed(0 , "mahogany seed",0,false),
    MushroomTreeSeed(0 , "mushroom tree seed" , 0 , false),
    Milk(125 , "milk" , 50 , true),
    SilverMilk(156 , "silver milk" , 52 , true),
    GoldMilk(188 , "gold milk" , 54 , true),
    IridMilk(250 , "irid milk" , 56 , true),
    BigMilk(190 , "big milk" , 75 , true),
    SilverBigMilk(238 , "silver big milk" , 78 , true),
    GoldBigMilk(285 , "gold big milk" , 82 , true),
    IridBigMilk(380 , "irid big milk" , 85 , true),
    GoatMilk(225 , "goat milk" , 60 , true),
    SilverGoatMilk(281 , "silver goat milk" , 62 , true),
    GoldGoatMilk(338 , "gold goat milk" , 65 , true),
    IridGoatMilk(450 , "irid goat milk" , 70 , true),
    BigGoatMilk(345 , "big goat milk" , 85 , true),
    SilverBigGoatMilk(431 , "silver big goat milk" , 88 , true),
    GoldBigGoatMilk(518 , "gold big goat milk" , 92 , true),
    IridBigGoatMilk(690 , "irid big goat milk" , 95 , true),
    Wool(340 , "wool" , 0 , false),
    SilverWool(425 , "silver wool" , 0 , false),
    GoldWool(510 , "gold wool" , 0 , false),
    IridWool(680 , "irid wool" , 0 , false),
    Truffle(625 , "truffle" , 42 , true),
    SilverTruffle(781 , "silver truffle" , 45 , true),
    GoldTruffle(938 , "gold truffle" , 48 , true),
    IridTruffle(1250 , "irid truffle" , 50 , true),
    Egg(50 , "egg" , 75 , true),
    SilverEgg(63 , "silver egg" , 78 , true),
    GoldEgg(75 , "gold egg" , 80 , true),
    IridEgg(100 , "irid egg" , 85 , true),
    BigEgg(95 , "big egg" , 90 , true),
    SilverBigEgg(119 , "silver big egg" , 93 , true),
    GoldBigEgg(143 , "gold big egg" , 96 , true),
    IridBigEgg(190 , "irid big egg" , 100 , true),
    DuckEgg(95 , "duck egg" , 90 , true),
    SilverDuckEgg(119 , "silver duck egg" , 93 , true),
    GoldDuckEgg(143 , "gold duck egg" , 96 , true),
    IridDuckEgg(190 , "irid duck egg" , 100 , true),
    DuckFeather(250 , "duck feather ", 0 , false),
    SilverDuckFeather(313 , "silver duck feather ", 0 , false),
    GoldDuckFeather(375 , "gold duck feather ", 0 , false),
    IridDuckFeather(500 , "irid duck feather ", 0 , false),
    RabbitLeg(565 , "rabbit leg" , 0 , false),
    SilverRabbitLeg(706 , "silver rabbit leg" , 0 , false),
    GoldRabbitLeg(848 , "gold rabbit leg" , 0 , false),
    IridRabbitLeg(1130 , "irid rabbit leg" , 0 , false),
    DinosaurEgg(350 , "dinosaur egg" , 150 , true),
    SilverDinosaurEgg(438 , "silver dinosaur egg" , 155 , true),
    GoldDinosaurEgg(525 , "gold dinosaur egg" , 160 , true),
    IridDinosaurEgg(700 , "irid dinosaur egg" , 165 , true),
    ApricotTreeSapling(100 , "Apricot Tree Sapling" , 0 , false),
    CherryTreeSapling(100,"Cherry Tree Sapling",0,false),
    BannaTreeSapling(100 , "banananan sapling",0,false),
    MangoTreeSapling(100 , "mango tree sapling",0,false),
    OrangeTreeSapling(100 , "orange tree sapling",0,false),
    PeachTreeSapling(100,"peachTreeSapling",0,false),
    AppleTreeSapling(100,"apple tree sapling",0,false),
    PomegranateTreeSapling(100 , "anare sapling",0,false),
    MysticTreeSeed(1000 , "mystic tree seed",0,false),
    OakResin(200,"oak resin" , 0 , false),
    Cherry(80,"cherry" , 38 , true),
    Banana(150 , "banana",75, true),
    Mango(130 , "mango", 100 , true),
    Orange(100 , "orange" , 38 , true),
    Peach(140 ,  "peach" , 38 , true),
    Apple(100 , "apple" , 100 , true),
    Pomegranate(100 , "pomegranate" , 140 , true),
    MapleSyrup(200 , "maple syrypm" , 0 , false),
    PineTar(100 , "pine tar" , 0 , false),
    Sap(2 , "sap" , -2  ,true),
    MysticSyrup(1000 , "mystic syrup", 500 , true),
    Shad(60 , "shad" , 0 , false),
    Discus(120 , "blue discus" , 0 , false),
    Garlic(20 , "garlic" , 10 , true),
    GreenBean(20  , "greenBeen" , 10 , true),
    Rhubarb(20 , "Rhubarb" , 20 , true),
    Strawberry(20 , "Strawberry" , 20 , true),
    Tulip(20 , "Tulip" , 20 , true),
    UnmilledRice(20 , "UnmilledRice" , 20 , true),
    Hops(20 , "Hop" , 20 , true),
    HotPepper(20 , "HotPepper" , 20 , true),
    Poppy(20,"poppy" , 20 , true),
    Starfruit(20 , "Starfruit" , 20 , true),
    SummerSpangle(20 , "SummerSpangle" , 20 , true),
    Sunflower(20 , "Sunflower" , 20 , true),
    Artichoke(20 , "Artichoke" , 20 ,true),
    BokChoy(20 , "BokChoy" , 20 , true),
    Broccoli(20 , "Broccoli" , 20 , true),
    Cranberries(20 , "Cranberries", 20 , true),
    SweetGemBerry(20 , "SweetGemBerry" , 20 , true),
    Powdermelon(20 , "Powdermelon" , 20 , true),
    PowdermelonSeed(100 , "PowdermelonSeed" , 0 , false),
    AncientFruit(20 , "AncientFruit" , 20 , true),
    Honey(350 , "Honey" , 75 , true),
    Cheese(230 , "Cheese" , 100 , true),
    BigCheese(345 , "Big Cheese" , 100 , true),
    GoatCheese(400 , "Goat Cheese" , 100 , true),
    BigGoatCheese(600 , "Big Goat Cheese" , 100 , true),
    Beer(200 , "Beer" , 50 , true),
    Vinegar(100 , "Vinegar" , 13 , true),
    Coffee(150 , "Coffee" , 75 , true),
    Juice(180 , "Juice" , 100 , true),
    Mead(300 , "Mead" , 100 , true),
    PaleAle(300 , "PaleAle" , 50 , true),
    Wine(400 , "Wine" , 80 , true),
    DriedMushrooms(1000 , "Dried Fruit" , 50 , true),
    DriedFruit(1000 , "Juice" , 75 , true),
    Raisins(600 , "Raisins" , 125 , true),
    Coal(50 , "Coal" , 0 , false),
    Cloth(470 , "Cloth" , 0 , false),
    Mayonnaise(190 , "Mayonnaise" , 50 , true),
    BigMayonnaise(237 , "Big Mayonnaise" , 50 , true),
    DuckMayonnaise(337 , "Duck Mayonnaise" , 75 , true),
    DinosaurMayonnaise(800 , "Dinosaur Mayonnaise" , 125 , true),
    TruffleOil(1065 , "Truffle Oil" , 38 , true),
    Oil(100 , "Oil" , 13 , true),
    Pickles(150 , "Pickles" , 100 , true),
    Jelly(200 , "Jelly" , 150 , true),
    SmokedFish(100 , "Smoked Fish" , 50 , true),
    CopperBar(50,"copper bar" , 0 , false),
    IronBar(100,"iron bar" , 0 , false),
    GoldBar(250,"gold bar" , 0 , false),
    IridiumBar(1000,"iridium bar" , 0 , false),

    Squid(80 , "Squid" , 20 , true),
    Tuna(100 , "Tuna" , 20 , true),
    Perch(55 , "perch" , 20 , true),
    LionFish(100 , "LionFish" , 20 , false),
    Herring(30 , "Herring" , 20 , true),
    GhostFish(45 , "ghost fish" , 20 , true),
    Tilapia(75 , "Tilapia" , 20 , true),
    Dorado(100 , "Dorado" , 20 , true),
    Sunfish(30 , "Sunfish" , 20 , false),
    RainbowTrout(65 , "RainbowTrout", 30 , false),
    Legend(5000 , "Legend" , 0 , false),
    Glacierfish(1000 , "Glacierfish" , 0 , false),
    Angler(900 , "Angler" , 0 , false),
    Crimsonfish(1500 , "Crimsonfish" , 0 , false),


    FriedEgg(35,"fried egg" , 50 , true),
    BackedFish(100,"backed fish" , 75,true),
    Salad(110 , "salad" , 113 , true),
    Omelet(125, "omelet" , 100 , false),
    PumpkinPie(385, "pumpkin pie" , 225 , true),
    Spaghetti(120 , "spaghetti" , 75, true),
    Pizza(300 , "pizza" , 150 , true),
    Tortilla(50 , "tortilla" , 50 , true),
    MakiRoll(220 , "MakiRoll" , 110 , true),
    TripleShotEspresso(450 , "TripleShotEspresso" , 200 , true),
    Cookie(140 , "Cookie" , 90 , true),
    HashBrowns(120 , "HashBrowns" , 90 , true),
    Pancakes(80 , "Pancakes" , 90 , true),
    FruitSalad(450 , "FruitSalad" , 263 , true),
    RedPlate(400 , "RedPlate" , 240 , true),
    Bread(60, "bread" , 50 , true),
    SalmonDinner(300 , "SalmonDinner" , 125 , true),
    VegetableMedley(120 , "VegetableMedley" , 165 , true),
    FarmersLunch(150 , "FarmersLunch" , 200 , true),
    SurvivalBurger(180 , "SurvivalBurger" , 125 , true),
    DishOTheSea(220 , "DishOTheSea" , 150 , true),
    SeaFormPudding(300 , "SeaFormPudding" , 175 , true),
    MinersTreat(200 , "MinersTreat" , 125, true),


    CherryBomb(50 , "cherry bomb" , 0 , false),
    Bomb(50 , "bomb" , 0 , false),
    MegaBomb(50 , "mega bomb" , 0 , false),
    Sprinkler(0 , "sprinkler" , 0 , false),
    QualitySprinkler(0 , "quality sprinkler" , 0 , false),
    IridiumSprinkler(0 , "iridium sprinkler" , 0 , false),
    CharcoalKlin(0 , "charcoal klin" , 0 , false),
    Furnace(0 , "furnace" , 0 , false),
    Scarecrow(0 , "scarecrow" , 0 , false),
    DeluxeScarecrow(0 , "deluxe scarecrow" , 0 , false),
    CheesePress(0 , "cheese press" , 0 , false),
    Keg(0 , "keg" , 0 , false),
    Loom(0 , "loom" , 0 , false),
    MayonnaiseMachine(0 , "mayonnaise machine" , 0 , false),
    OilMaker(0 , "oil maker" , 0 , false),
    PreservesJar(0 , "preserves jar" , 0 , false),
    Dehydrator(0 , "dehydrator" , 0 , false),
    GrassStarter(0 , "grass starter" , 0 , false),
    FishSmoker(0 , "fish smoker" , 0 , false),

    ;




    private final int price ;
    private final String disPlayName;
    private final int energy;
    private final boolean isEdible;

    ItemType(int price, String disPlayName, int energy, boolean isEdible) {
        this.price = price;
        this.disPlayName = disPlayName;
        this.energy = energy;
        this.isEdible = isEdible;
    }

    public int getPrice() {
        return price;
    }

    public String getDisPlayName() {
        return disPlayName;
    }

    public int getEnergy() {
        return energy;
    }

    public boolean isEdible() {
        return isEdible;
    }

    public static boolean isItem(String itemName) {
        try {
            ItemType.valueOf(itemName);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    public static ItemType getItembyname(String itemName){
        if(itemName==null || itemName.isEmpty()) return null;
        for(ItemType type : ItemType.values()){
            if(type.name().equalsIgnoreCase(itemName.toLowerCase())) return type;
        }
        return null;
    }


    public static ItemType getItemType(String type) {
        try {
            return ItemType.valueOf(type);
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    public ItemType getKind(String KIND){
        String kind = KIND+this.name();
        return ItemType.valueOf(kind);
    }

}
